Repository balena-io/balena-sdk, pull requests merged in 2018-07, with the labels that each got.

#534 Upgrade uglify & include (now-supported) streaming dependencies
  CHANGELOG.md
  README.md
  gulpfile.coffee
  package.json
  yarn.lock
Labels: procbots/versionbot/ready-to-merge

#537 Print a 'please update' warning if any legacy SDK logs methods are used
  CHANGELOG.md
  lib/logs.coffee
  lib/util/deprecation-warnings.ts
  package.json
  yarn.lock
Labels: procbots/versionbot/ready-to-merge

#529 Use the API's custom endpoint for reading device logs
  .travis.yml
  CHANGELOG.md
  DOCUMENTATION.md
  karma.conf.coffee
  lib/logs.coffee
  lib/resin.coffee
  lib/util/index.coffee
  package.json
  tests/integration/logs.spec.coffee
  typings/resin-sdk.d.ts
  yarn.lock
Labels: enhancement, procbots/versionbot/ready-to-merge

#543 Pin bluebird typings to the latest working version
  CHANGELOG.md
  package.json
  yarn.lock
Labels: procbots/versionbot/ready-to-merge

#545 Use a new npm token to fix travis deploys
  .travis.yml
  CHANGELOG.md
  package.json
Labels: procbots/versionbot/ready-to-merge

#546 Document getConfig's limitations when using API keys
  DOCUMENTATION.md
  lib/models/os.coffee
Labels: procbots/versionbot/no-checks

#549 Add logs history & subscribe options to the TS typings
  CHANGELOG.md
  package.json
  typings/resin-sdk.d.ts
Labels: procbots/versionbot/ready-to-merge

#551 typings: Update to be compatible with TS 2.9
  typings/pinejs-client-core.d.ts
  typings/resin-pine.d.ts
  typings/resin-sdk.d.ts
Labels: procbots/versionbot/no-checks

#553 Deprecate generate api key
  DOCUMENTATION.md
  lib/models/application.coffee
  lib/models/device.coffee
Labels: procbots/versionbot/no-checks
